### ISSUE TITLE
[20 BETA] Incorrect Storage Units (SI)

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1815]
## Describe the bug
Some parts of the system (including deepin's apps) do not display storage units correctly in the International System of Units (SI). Below is a list of these units and symbols:

**_**byte (B)
kilobyte (kB)**_** - _the letter "k" is lowercase_
**_**megabyte (MB)
gigabyte (GB)
terabyte (TB)
petabyte (PB)
exabyte (EB)
zettabyte (ZB)
yottabyte (YB)**_**

## Screenshots
deepin File Manager
![Screen Capture_select-area_20200711210408](https://user-images.githubusercontent.com/45263160/87236021-13b23180-c3ba-11ea-9f54-796e4a9da4f6.png)

deepin Music
![Screen Capture_deepin-music_20200711211632](https://user-images.githubusercontent.com/45263160/87236144-d3ec4980-c3bb-11ea-9f8c-7cf124cdb96d.png)

deepin System Monitor
![Screen Capture_select-area_20200711210817](https://user-images.githubusercontent.com/45263160/87236075-a94dc100-c3ba-11ea-8840-144ce9ad14a5.png)

deepin Installer Reborn
![photo4916112042398689406](https://user-images.githubusercontent.com/45263160/87236147-d9e22a80-c3bb-11ea-82e3-d8ba0486cdc4.jpg)

![photo4916112042398689407](https://user-images.githubusercontent.com/45263160/87236149-dcdd1b00-c3bb-11ea-9e59-8b32fbb1b987.jpg)

### Distro & Version
deepin 20 BETA

### Additional context
The display of the letters (K, M, G ...) do not refer to the storage units. This is a very serious mistake..

**Comment by xmuli** [comment]
Thanks for the suggestion, we already received one of these two days ago (from a colleague) and I've already passed it on to the product manager (I personally think it was corrected)

**Comment by alexwender1** [comment]
> Thanks for your suggestion, we have received my suggestion two days ago (a colleague) and I have forwarded it to the product manager (I think you are right)

Yes, I talked to Cindy (or "zhuxiujuancindy", I don't know her name).

**Comment by xmuli** [comment]
See the name, that's her (I know her:  “zhuxiujuancindy”). (Because posting here again, you can also see the progress if others later on can also reply to comments here, if (If someone comes to update)

**Comment by alexwender1** [comment]
In version 1003 (Update 1), the problems still persist.

In the Control Center, there is another problem with units. The correct one is "2.4 GHz".

![Captura de Tela_select-area_20201129090726](https://user-images.githubusercontent.com/45263160/100670706-07654b80-333e-11eb-87bb-f3382425b7c2.png)

MajorVersion=20
MinorVersion=1003
OsBuild=11031.106

dde-control-center 5.3.0.80-1

**Comment by alexwender1** [comment]
The problem persists in the new version: deepin 20.1 (1010) / OsBuild=11031.108

Note: Only the display of the size of the songs has been corrected.

**Comment by alexwender1** [comment]
The same problem occurs in the Disk Utility application:

![Captura de Tela_deepin-diskmanager_20201230151609](https://user-images.githubusercontent.com/45263160/103372979-61c70880-4ab2-11eb-876d-4198ba75f811.png)

deepin-diskmanager 1.1.0.34-1

**Comment by alexwender1** [comment]
Compressor is not left out either...

![Captura de Tela_deepin-compressor_20201221184640](https://user-images.githubusercontent.com/45263160/103373077-b36f9300-4ab2-11eb-94f0-f7a1874ebaca.png)
**kB/s is correct!** (with the lowercase "k" and "s")

<br>

![Captura de Tela_deepin-compressor_20201221184645](https://user-images.githubusercontent.com/45263160/103373082-b7031a00-4ab2-11eb-855d-3d992ab97fb2.png)
**MB/s is correct!** (with the lowercase "s"

deepin-compressor 5.9.0.9-1

**Comment by zhuxiujuancindy** [comment]
> The same problem occurs in the Disk Utility application:
> 
> ![Captura de Tela_deepin-diskmanager_20201230151609](https://user-images.githubusercontent.com/45263160/103372979-61c70880-4ab2-11eb-876d-4198ba75f811.png)
> **MB and GB is correct!**
> 
> 
> deepin-diskmanager 1.1.0.34-1

The developers said MiB is right, see https://en.wikipedia.org/wiki/Kilobyte

**Comment by zhuxiujuancindy** [comment]
Other problems have been forwarded to the product manager and will be fixed in next versions.

**Comment by lxwndr** [comment]
> > O mesmo problema ocorre no aplicativo Utilitário de Disco: 
> > ![Captura de Tela_deepin-diskmanager_20201230151609](https://user-images.githubusercontent.com/45263160/103372979-61c70880-4ab2-11eb-876d-4198ba75f811.png)
> > **MB e GB estão corretos! **
> > deepin diskmanager 1.1.0.34-1
> 
> Os desenvolvedores disseram que o MiB está certo, consulte [https://en.wikipedia.org/wiki/Kilobyte ](https://en.wikipedia.org/wiki/Kilobyte)

It is not incorrect, but it is not ideal. The world standard is _decimal_ nomenclature (Megabite / MB) instead of binary (Mebibyte / MiB).

Have you ever seen a disc with 1 TiB (Tebibyte)? I only see terabyte (TB) disks, for example.

**Comment by lxwndr** [comment]
Another problem is the display of the VFAT file system of the removable storage devices in the File Manager.

All users are familiar with the FAT (FAT16) and FAT32 formats... When displaying VFAT instead of FAT or FAT32, users are confused.

**Comment by lxwndr** [comment]
@meiyixiang

**Comment by meiyixiang** [comment]
Hello, the system monitor, file properties and other related units you feedback have been modified, please upgrade to the latest version

**Comment by lxwndr** [comment]
Some reported problems still persist in the latest version of the system/applications:

1. System installer (deepin 20.4)

![photo5003499525767276990](https://user-images.githubusercontent.com/45263160/158085728-d0166d2f-72e5-4a89-8ff1-2c594f7280d6.jpg)

![photo5003499525767276989](https://user-images.githubusercontent.com/45263160/158085732-2618c1ed-a65f-461e-8cdb-a64a34eeab25.jpg)

2. dde-file-manager 5.5.8-1

![Capturar_select-area_20220313143100](https://user-images.githubusercontent.com/45263160/158085820-97b65c3e-adc1-458c-a3e0-7f9fbfb47165.png)

3. dde-control-center 5.5.16.2-1

![Capturar_select-area_20220313205817](https://user-images.githubusercontent.com/45263160/158085906-d7edbb53-f184-422b-a11b-fd40697b8d6b.png)

4. deepin-diskmanager 1.3.3-1

![Capturar_deepin-diskmanager_20220313211121](https://user-images.githubusercontent.com/45263160/158085991-b1d3e243-6bfb-48b8-ba4c-1aa900e17061.png)

_$ cat /etc/os-version
[Version] 
SystemName=Deepin
SystemName[zh_CN]=深度操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Community
EditionName[zh_CN]=社区版
MajorVersion=20
MinorVersion=20.5
OsBuild=11038.005_

**Comment by lxwndr** [comment]
5. dde-control-center 5.5.16.2-1

![Capturar_dde-control-center_20220313212704](https://user-images.githubusercontent.com/45263160/158086325-1a1e975e-2047-4da8-bdcd-e6d235e2eb31.png)

Note: The correct is "100 Mbps"

**Comment by meiyixiang** [comment]
Thank you for your advice and rigor. I have submitted this problem and will revise it as soon as possible

**Comment by meiyixiang** [comment]
This kind of problem has been modified in DDE, and other self-developed applications developed and maintained by different projects will be modified in subsequent stages.
