### ISSUE TITLE
icons cannot be changed from the default

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#184]
Since latest updated it is not possible to change the icon theme on Manjaro. The default gsettings will always be used and attempts to switch the theme in the control center ignored.

**Comment by foliea** [comment]
beside some icons fallback to the default icon (like slack), even if its perfectly working in the the applications menu.
![deepinscreenshot20170303003332](https://cloud.githubusercontent.com/assets/2271115/23531897/0e8a0c06-ffa9-11e6-93f7-2a1ab2e35321.png)

![deepinscreenshot20170303003245](https://cloud.githubusercontent.com/assets/2271115/23531884/f0c1380c-ffa8-11e6-8482-461cabf53332.png)

**Comment by hualet** [comment]
I think this problem has been solved, right? @zccrs @sbwtw

**Comment by hualet** [comment]
@felixonmars Meow... Can you test the latest version of dde-dock for us, on Arch ?

**Comment by felixonmars** [comment]
Confirmed that the issue is no longer present in latest git master. How about a new tag?

**Comment by zccrs** [comment]
@felixonmars Let @sbwtw  make a new tag for you

**Comment by oberon2007** [comment]
I'm afraid the issue is still present for me with **dde-dock 4.1.4** :disappointed:

**Comment by michaldybczak** [comment]
Confirmed, icons still won't change after update.

**Comment by funilrys** [comment]
Same here same version as @oberon2007

**Comment by felixonmars** [comment]
Icon theme changes are working correctly here after the upgrade :/

**Comment by oberon2007** [comment]
Could you maybe let me know what has been changed in your end that fixes it for you or what caused your issue in the first place? So I can maybe investigate what might still be off here? Looks like all the users still with this issue are using Manjaro if I'm not wrong...

**Comment by michaldybczak** [comment]
I use Manjaro Deepin release. Maybe it would worth a try to install/use live Manjaro other release in virtualbox and then install deepin to see if the problem appears there. This way we could find out if there is something on Manjaro Deepin release that is messing it.

Unless there is a way to see some debug messages for that action...

**Comment by oberon2007** [comment]
@michaldybczak Manjaro uses customized **dde-session-ui** and **deepin-desktop-schemas**. They are up-to-date with latest upstream releases. You can try exchanging them for their corresponding Archlinux packages but you'll have to remove **manjaro-deepin-settings** for that, which depends on the Manjaro versions. I was only able to try that in  live session as I've currently no Deepin install available. So, without a reboot in any case I still had the same issue like that. **deepin-dock** in any case we use Archlinux upstream.

**Comment by oberon2007** [comment]
@michaldybczak I just pushed a new package **deepin-desktop-schemas-manjaro-3.1.1-2** to unstable branch. Maybe you'd like to try if that makes a difference until I have to opportunity later to test it myself.

**Comment by oberon2007** [comment]
Ok. So I have investigated more :wink: 
In fact icons are changing fine in the launcher and first it seemed like the dock would not change - not even after re-logging. But killing the dock with ``pkill dde-dock`` makes it come up with the new icons and from then on the icons will follow the changes in the control-center.
Just, why is it like that? Something is not completely right still, I think ...

**Comment by oberon2007** [comment]
For me it's like this:
Changing icons doesn't effect the dock until I restart dde-dock. After that icon changes are applied to the dock. But:
When I log out and back in after that, the dock will come up again with deepin icons in the new session. :stuck_out_tongue_winking_eye:
(this is already with https://github.com/linuxdeepin/dde-dock/commit/67dc811f6750602122397e67739882196cf72534) 
@sbwtw any ideas or helpful output I can provide? Problem is restarting dde-dock in debug mode won't help because the issue is not present after killing it once :laughing:

**Comment by michaldybczak** [comment]
I'm on stable. Updated deepin-dock to 4.1.4-1 and it didn't help, I get exactly the same behaviour as yours. Killing dock fixes it but only for the time of current session.
There has to be something during session boot that interferes with it or is not loading right. Some detailed logs of session boot would be handy.

On irc manjaro channel I met someone who also complained on this issue, so it's persistent and reproducible.

**Comment by oberon2007** [comment]
The issue is still present with **v4.1.6** I'm afraid @sbwtw :stuck_out_tongue_winking_eye: 
Also icons of desktop items are not changing btw...

**Comment by sbwtw** [comment]
sorry. @oberon2007 
i did not see this issue before. but it's worked in Deepin.
I think, how about give you a patch to add some debug info to find problem

**Comment by sbwtw** [comment]
please apply this patch add upload your ~/.cache/deepin/dde-dock/dde-dock.log

**Comment by oberon2007** [comment]
Thank you. will get back to you soon! :)

**Comment by oberon2007** [comment]
@sbwtw the patch is a binary... How do I apply it? Not to the source? To the exacutable? How? :wink:

**Comment by sbwtw** [comment]
[patch.zip](https://github.com/linuxdeepin/developer-center/files/840144/patch.zip)
maybe is break when i upload. try this zip.
using `git am xxx`

**Comment by oberon2007** [comment]
this one is better! :wink: :+1:

**Comment by oberon2007** [comment]
Hm. Not sure if this is very helpful for you...
I get a lot of these:
```
"deepin-launcher" 32
2017-03-13, 15:44:50.116 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.119 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-launcher" 43
2017-03-13, 15:44:50.119 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.131 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "dde-file-manager" 32
2017-03-13, 15:44:50.131 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-13, 15:44:50.133 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.144 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "dde-file-manager" 43
2017-03-13, 15:44:50.153 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-13, 15:44:50.154 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.157 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "chromium" 32
2017-03-13, 15:44:50.158 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-13, 15:44:50.159 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.167 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "chromium" 43
2017-03-13, 15:44:50.167 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-13, 15:44:50.169 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.192 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-terminal" 32
2017-03-13, 15:44:50.192 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-13, 15:44:50.194 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.201 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-terminal" 43
2017-03-13, 15:44:50.202 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-13, 15:44:50.203 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.221 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-show-desktop" 32
2017-03-13, 15:44:50.221 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.225 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-show-desktop" 43
2017-03-13, 15:44:50.225 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.239 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-multitasking-view" 32
2017-03-13, 15:44:50.239 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.243 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-multitasking-view" 43
2017-03-13, 15:44:50.243 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-13, 15:44:50.249 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) 
```
It looks the same after killling and relaunching the dock, when the new icons are applied.
Still I see all these "loading from default theme" ?

**Comment by sbwtw** [comment]
whats your version of dde-qt5integration

**Comment by oberon2007** [comment]
**v0.1.3*

**Comment by oberon2007** [comment]
it's the latest as far as I can see...

**Comment by sbwtw** [comment]
@oberon2007  please test:
1. change icon theme in dde-control-center
2. change dock position (with dde-dock popup menu)
if icon theme not changed, test remove all plugins (/usr/lib/dde-dock/plugins/lib*.so at deepin) and restart dde-dock, then do 1 and 2.

**Comment by oberon2007** [comment]
Unfortunately doesn't make any difference. :disappointed: 
The only advantage you could say that now I have less (default) icons altogether in the dock :stuck_out_tongue_winking_eye: :laughing:

**Comment by michaldybczak** [comment]
Uh, all that sounds scary. Will wait patently till you all get to the root of it. Thanks! 👍

**Comment by sbwtw** [comment]
[patch.zip](https://github.com/linuxdeepin/developer-center/files/843260/patch.zip)

apply this patch and run dde-dock, after icon theme changed, you should see some log like this:

2017-03-15, 10:26:18.606 [Debug  ] [docksettings.cpp     DockSettings::gtkIconThemeChanged   456] =================================================================================== void DockSettings::gtkIconThemeChanged()
2017-03-15, 10:26:18.606 [Debug  ] [dockitemcontroller.cpp DockItemController::refershItemsIcon 47] ==================================================================== void DockItemController::refershItemsIcon()
2017-03-15, 10:26:18.606 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(const QString, const int) "deepin-launcher" 32
2017-03-15, 10:26:18.606 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 10:26:19.790 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "deepin-launcher" "flattr"
2017-03-15, 10:26:19.872 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(const QString, const int) "deepin-launcher" 43
2017-03-15, 10:26:19.872 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 10:26:19.872 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "deepin-launcher" "flattr"

**Comment by oberon2007** [comment]
Thank you, @sbwtw ! Here you are:
```
2017-03-15, 04:23:49.935 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:23:49.935 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "deepin-multitasking-view" "deepin"
2017-03-15, 04:23:49.954 [Debug  ] [appitem.cpp          AppItem::refershIcon                397] virtual void AppItem::refershIcon()
2017-03-15, 04:23:49.955 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "preferences-system" 336
2017-03-15, 04:23:49.956 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:23:49.956 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "preferences-system" "deepin"
2017-03-15, 04:23:49.993 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "preferences-system" 432
2017-03-15, 04:23:49.993 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:23:49.993 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "preferences-system" "deepin"
2017-03-15, 04:23:50.094 [Debug  ] [dockitemcontroller.cpp DockItemController::refershItemsIcon 47] ==================================================================== void DockItemController::refershItemsIcon()
2017-03-15, 04:23:50.095 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-launcher" 288
2017-03-15, 04:23:50.095 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:23:50.095 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "deepin-launcher" "deepin"
2017-03-15, 04:23:50.115 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-launcher" 384
2017-03-15, 04:23:50.116 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:23:50.116 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "deepin-launcher" "deepin"
2017-03-15, 04:23:50.133 [Debug  ] [appitem.cpp          AppItem::refershIcon                397] virtual void AppItem::refershIcon()
2017-03-15, 04:23:50.161 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "dde-file-manager" 288
```

**Comment by oberon2007** [comment]
And here's after kill / restart the dock. Icons changed:
```
dde-dock startup
2017-03-15, 04:34:50.361 [Debug  ] [appitem.cpp          AppItem::refershIcon                397] virtual void AppItem::refershIcon()
2017-03-15, 04:34:50.362 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "dde-file-manager" 336
2017-03-15, 04:34:50.362 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-15, 04:34:50.365 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:34:50.366 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "dde-file-manager" "Sea"
2017-03-15, 04:34:50.371 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "dde-file-manager" 432
2017-03-15, 04:34:50.372 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-15, 04:34:50.373 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:34:50.373 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "dde-file-manager" "Sea"
2017-03-15, 04:34:50.382 [Debug  ] [appitem.cpp          AppItem::refershIcon                397] virtual void AppItem::refershIcon()
2017-03-15, 04:34:50.383 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "chromium" 336
2017-03-15, 04:34:50.384 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-15, 04:34:50.385 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:34:50.385 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "chromium" "Sea"
2017-03-15, 04:34:50.398 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "chromium" 432
2017-03-15, 04:34:50.398 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               40] loading from exist file
2017-03-15, 04:34:50.399 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               46] loading from default theme
2017-03-15, 04:34:50.399 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               48] "chromium" "Sea"
2017-03-15, 04:34:50.416 [Debug  ] [appitem.cpp          AppItem::refershIcon                397] virtual void AppItem::refershIcon()
2017-03-15, 04:34:50.419 [Debug  ] [themeappicon.cpp     ThemeAppIcon::getIcon               19] static const QPixmap ThemeAppIcon::getIcon(QString, int) "deepin-terminal" 336
```

**Comment by sbwtw** [comment]
@oberon2007 its load icon from "deepin" icon theme. and i dont see "gtkIconThemeChanged" output.
please upload log after you change the icon theme at dde-control-center (or maybe problem is dde-dock not receive the icon theme changed signal?)

**Comment by sbwtw** [comment]
oh。 seems dde-dock not received the theme changed signal :(

**Comment by oberon2007** [comment]
You have scroll to the right in the first of my two log posts: 
``=== void DockItemController::refershItemsIcon()``

**Comment by oberon2007** [comment]
No ``DockSettings::gtkIconThemeChanged``, exactly!

**Comment by sbwtw** [comment]
okey, please paste version of dde-launcher and libdtkwidget

**Comment by oberon2007** [comment]
**deepin-launcher 4.0.8**
**libdtkwidget** doesn't exist on Archlinux. I have **deepin-tool-kit** 0.2.6 ... that one?

**Comment by oberon2007** [comment]
yes, ``/usr/lib/libdtkwidget.so is owned by deepin-tool-kit 0.2.6-2``

**Comment by oberon2007** [comment]
ubdating to **deepin-tool-kit 0.2.7** right now ...

**Comment by oberon2007** [comment]
no difference with latest package update... :disappointed:

**Comment by sbwtw** [comment]
Strange bug... I'm downloading manjaro 16.10.3 ISO to find problem.

**Comment by hualet** [comment]
@oberon2007 version of dde-qt5integration? it should be 0.1.3.

**Comment by oberon2007** [comment]
@sbwtw that ISO is old. I can build one with latest pkgs and send you a link later. Thank you for bothering!

**Comment by oberon2007** [comment]
:laughing: I have good news and bad news:
* the icon issue is solved. Reason was **qt5ct**. Icon theme was defined there and apparently blocking icon update
* bad news is that with the latest update of **deepin-daemon** to **3.1.5**, the dock won't start at all :wink: It fails with
```
dde-dock startup
2017-03-16, 06:20:15.152 [Debug  ] [diskmountplugin.cpp  DiskMountPlugin::DiskMountPlugin    15] ===============init=============
2017-03-16, 06:20:15.152 [Debug  ] [diskmountplugin.cpp  DiskMountPlugin::init               34] ===============init== proxyInter===========
2017-03-16, 06:20:15.155 [Debug  ] [qsettingbackend.cpp  Dtk::QSettingBackend::QSettingBackend 36] create config "/home/neu/.config/dde-file-manager/dde-file-manager.conf"
2017-03-16, 06:20:15.229 [Debug  ] [partition.cpp        PartMan::Partition::getPartitionByDevicePath 67] read usgae of "/dev/sda2" false
2017-03-16, 06:20:15.230 [Debug  ] [gvfsmountmanager.cpp GvfsMountManager::updateDiskInfos   786] QDiskInfo(id: "/dev/sda2",name: "430 GB Volume",type: "native",unix_device: "/dev/sda2",uuid: "72e14924-035c-404b-9138-0937ce495158",activation_root_uri: "",mounted_root_uri: "",id_filesystem: "",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: true,can_unmount: false,can_eject: false,used: 0,total: 0,)
2017-03-16, 06:20:15.230 [Debug  ] [gvfsmountmanager.cpp GvfsMountManager::updateDiskInfos   812] QMap()
2017-03-16, 06:20:15.231 [Debug  ] [diskcontrolwidget.cpp DiskControlWidget::onDiskListChanged 55] =============== QMap(("/dev/sda2", QDiskInfo(id: "/dev/sda2",name: "430 GB Volume",type: "native",unix_device: "/dev/sda2",uuid: "72e14924-035c-404b-9138-0937ce495158",activation_root_uri: "",mounted_root_uri: "",id_filesystem: "",default_location: "",iconName: "drive-harddisk",is_removable: false,can_mount: true,can_unmount: false,can_eject: false,used: 0,total: 0,)))
2017-03-16, 06:20:15.231 [Debug  ] [diskmountplugin.cpp  DiskMountPlugin::diskCountChanged   117] 0 false
2017-03-16, 06:20:15.921 [Warning] [                                                         0] QPainter::begin: Paint device returned engine == 0, type: 2
2017-03-16, 06:20:15.921 [Warning] [                                                         0] QPainter::save: Painter not active
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::setRenderHint: Painter must be active to set rendering hints
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::setRenderHint: Painter must be active to set rendering hints
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::brush: Painter not active
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::pen: Painter not active
2017-03-16, 06:20:15.922 [Warning] [                                                         0] QPainter::pen: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::worldTransform: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::setWorldTransform: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::brush: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::opacity: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::brush: Painter not active
2017-03-16, 06:20:15.923 [Warning] [                                                         0] QPainter::pen: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::setOpacity: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::drawPath: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::setOpacity: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::drawPath: Painter not active
2017-03-16, 06:20:15.924 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::setOpacity: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::brush: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::opacity: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::brush: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::pen: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.925 [Warning] [                                                         0] QPainter::setOpacity: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setOpacity: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setOpacity: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setWorldTransform: Painter not active
2017-03-16, 06:20:15.926 [Warning] [                                                         0] QPainter::setBrush: Painter not active
2017-03-16, 06:20:15.927 [Warning] [                                                         0] QPainter::setPen: Painter not active
2017-03-16, 06:20:15.927 [Warning] [                                                         0] QPainter::restore: Unbalanced save/restore
2017-03-16, 06:20:15.927 [Warning] [                                                         0] QPainter::end: Painter not active, aborted
```

**Comment by sbwtw** [comment]
good !
I think this problem is caused by dde-daemon. maybe is blocked at some dbus call.
you can try to delete all dock plugins and try again.
@jouyouyun

**Comment by oberon2007** [comment]
Doesn't help unfortunately and I also have issue with control-center... I've opened a [new ticket](https://github.com/linuxdeepin/dde-daemon/issues/34) at dde-daemon :wink:
