### ISSUE TITLE
[manjaro] User trash dirs not created under manjaro

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/developer-center#52]
<a href="https://github.com/oberon2007"><img src="https://avatars.githubusercontent.com/u/11800714?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @oberon2007**
_Saturday Oct 03, 2015 at 21:41 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/87_

----

When I right click on a desktop icon selecting 'delete' or 'properties' does nothing while the other entries of the context menu work fine.

**Comment by fasheng** [comment]
Looks solved in the latest manjaro-deepin iso, including works for the new added user.

**Comment by oberon2007** [comment]
have you tried for an added user? for root and for user 1000 I had included the dirs manually in the ISO because a recent test did not work for me. But it's possible though that something has changed recently. I'll try to verify...

**Comment by fasheng** [comment]
I didn't check the root, but 1000 and 1001 works for me.

**Comment by oberon2007** [comment]
root and 1000 works as I said because the folders have been included manually. But 1001 is a good sign! :wink:

**Comment by oberon2007** [comment]
https://bugs.launchpad.net/ubuntu/+source/glib2.0/+bug/1391811

**Comment by hualet** [comment]
I saw the "Fix Released" status in another duplicated entry https://bugs.launchpad.net/ubuntu/+source/glib2.0/+bug/1391807,  have you invested in it ? @oberon2007

**Comment by fasheng** [comment]
@oberon2007 So you mean this only occurred under manjaro-deepin livecd mode? OK, I will check it later.

**Comment by oberon2007** [comment]
Yes. I was not aware until now that it's only a problem in the live environment. The reason is overlayfs on the ISOs. Btw the proper location for Trash should be at **~/.local/share**!
**/.Trash-1000** is just what helps to solve the issue, but when this location is present it has precedence over the other location.
The bug is still present in any case. We'll solve it by creating the dirs at root level in the live environment only.
